name: demo triggers

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'

jobs:
  myjob1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 
        run: |
          echo "Event: ${{ github.event_name }}"