name: snakemake

on:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  dryrun-lint:
    runs-on: ubuntu-latest
    container:
      image: snakemake/snakemake:v7.32.4
    steps:
      - uses: actions/checkout@v4
      - name: Dry-run
        run: |
          snakemake \
            -s ./snakemake-workflow/workflow/Snakefile \
            --dry-run
      - name: Lint
        run: |
          snakemake \
            -s ./snakemake-workflow/workflow/Snakefile \
            --lint
 