name: hello checkout

on: push

jobs:
  myjob1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}