name: render quarto reports

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "quarto-report/**"
      - ".github/workflows/render-quarto.yml"

permissions:
  contents: write
  pages: write

jobs:
  render-quarto:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::ggplot2
            any::palmerpenguins
            any::rmarkdown

      - name: Run R script
        run: |
          print("Hello, world!")
        shell: Rscript {0}

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: quarto-report/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
